name: Linux Build
on: push
jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: b5d1688ae722538ba4dc8a7ec08820a08abfb93d
    - name: Install wget
      run: sudo apt-get install wget
    - name: Build C Code
      run: |
        wget https://github.com/openresty/luajit2/archive/refs/tags/v2.1-20240314.tar.gz
        wget https://github.com/vision5/ngx_devel_kit/archive/refs/tags/v0.3.3.tar.gz
        sudo apt-get install nginx
        wget https://github.com/openresty/lua-nginx-module/archive/refs/tags/v0.10.26.tar.gz
        wget https://github.com/openresty/lua-resty-core/archive/refs/tags/v0.1.28.tar.gz
        wget https://github.com/openresty/lua-resty-lrucache/archive/refs/tags/v0.13.tar.gz
    - name: extract and build
      run: |  
        tar -xzvf nginx-1.19.3.tar.gz
        tar -xzvf v2.1-20240314.tar.tar.gz
        tar -xzvf v0.3.3.tar.gz
        tar -xzvf v0.10.26.tar.gz
        tar -xzvf v0.1.28.tar.gz
        tar -xzvf v0.13.tar.gz
        cd luajit2-2.1-20240314
        sudo make install
        cd ../nginx-1.19.3/
        export LUAJIT_LIB=/usr/local/lib
        export LUAJIT_INC=/usr/local/include/luajit-2.1
        ./configure --prefix=/usr/sbin/nginx --with-ld-opt="-Wl,-rpath,/usr/local/lib"
        make -j2
